<EnzymeCalc>
    name:'Enzyme_Calc'
    id: Enzyme_Calc
    GridLayout:
        pos_hint: {'top': 1, 'center_x': .5}
        size_hint: (0.8, .08)
        cols: 1
    #        col_default_width:60
        rows: 1
#        row_default_height: 30
#        row_force_default: True
        spacing: 5
        Spinner:
            id: enzyme_spinner
            background_color: (1, 2, 1, 1)
            text: 'CHOOSE STARCH'
            color: (0,0,0,1)
#            font_size:20
    #            size_hint: None, None
            size: 300, 30
#            values: ''
            on_press:
                root.starch_spinner(self.text)
            on_text:
                root.enzyme_spinner(self.text)

    GridLayout:
        pos_hint: {'top': .9, 'center_x': .5}
        size_hint: (0.8, .75)
        cols: 2

    #        col_default_width:60
        rows: 11
#        row_default_height: 30
#        row_force_default: True
        spacing: 5
        font_size: dp(12)
        Label:
            text: 'STARCH DOSE: '
            text_size: self.size
            bold: True
            halign: 'left'
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        TextInput:
            input_filter: 'int'
            id:starch_dose
            text:''
            font_size: self.parent.font_size
            multiline: False
            on_text_validate:
                root.starch_dosing(self.text)

        Label:
            text: 'PRODUCTION t/h: '
            text_size: self.size
            bold: True
            halign: 'left'
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        TextInput:
            input_filter: 'int'
            id:production
            text:''
            font_size: self.parent.font_size
            multiline: False
            on_text_validate:
                root.productions(self.text)
        Label:
            text: 'CONSUMPTION: '
            text_size: self.size
            bold: True
            halign: 'left'
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            id:consumption
            text: 't/month'
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            text: 'SLURRY %: '
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        TextInput:
            input_filter: 'int'
            id:slurry_conc
            text:''
            font_size: self.parent.font_size
            multiline: False
            on_text_validate:
                root.slurry_concent(self.text)

        Label:
            text: 'FINAL STARCH %: '
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        TextInput:
            input_filter: 'int'
            id:final_conc
            text:''
            font_size: self.parent.font_size
            multiline: False
            on_text_validate:
                root.final_concent(self.text)

        Label:
            text: 'SLURRY WATER: '
            text_size: self.size
            bold: True
            halign: 'left'
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            id:slurry_water
            text: ' l/h'
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            text:'DILUTION WATER: '
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            id:dilution_water
            text: ' l/h: '
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            text: 'ENZYME FLOW: '
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            id: enzyme_flow
            text: ' l/h: '
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            text: 'WATER CONS.: '
            text_size: self.size
            bold: True
            halign: 'left'
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            id:water_cons
            text: ' m3/month'
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            text: 'ENZYME CONS.: '
            text_size: self.size
            bold: True
            halign: 'left'
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

        Label:
            id:enzyme_cons
            text: ' m3/month'
            bold: True
            text_size:self.size
            valign: 'middle'
            color: (0, 0, 0, 1)
            font_size: self.parent.font_size

    GridLayout:
        pos_hint: {'top': .15, 'center_x': .5}
        size_hint: (0.8, .10)
        cols: 1

    #        col_default_width:60
        rows: 1
#        row_default_height: 30
#        row_force_default: True
        spacing: 5
        Button:
            id: calculate
            text: 'Calculate'
            bold: True
#            text_size:self.size
            valign: 'middle'
            color: (0, 1, 0, 1)
#            font_size: 20
            on_press:
                root.enzyme_calculation()